apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
  labels:
    app: my-app
spec:
  # serviceName must match the name of the Headless Service
  serviceName: headless-service
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: my-app
        volumeMounts:
        - name: volume  
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
